version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: accesosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - accesos_net
  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: nestuser
      DB_PASSWORD: nestpass
      DB_NAME: accesosdb
    ports:
      - "3000:3000"
    networks:
      - accesos_net
  frontend:
    build: ./frontend
    container_name: app_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - accesos_net
volumes:
  postgres_data:
networks:
  accesos_net:
    driver: bridge